import '@/app/globals.css'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: '/img/favicon.ico'
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const supabase = createServerComponentClient({ cookies })

	const {
		data: { session }
	} = await supabase.auth.getSession()

	return (
		<html lang="en" className="scroll-smooth antialiased">
			<body className={inter.className}>{children}</body>
		</html>
	)
}
