import './globals.css'
import { Inter } from 'next/font/google'
import { PlayerContextProvider } from '@/components/playerContext'
import Player from '@/components/player'
import UserSessionProvider from '@/components/userSessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className="scroll-smooth antialiased">
			<body className={inter.className}>
				<UserSessionProvider>
					<PlayerContextProvider>
						{children}
						<Player />
					</PlayerContextProvider>
				</UserSessionProvider>
			</body>
		</html>
	)
}
